### ISSUE TITLE
in Cocoapods the latest version is 0.1.0

### ISSUE THREAD

**Issue by akoskomuves** [kiliankoe/Karte#13]
Please update your repo to be available on cocoapods with the newest (1.1.0) version. 

p.s.: i really like this pod, exactly what i'm looking for 👌

**Comment by kiliankoe** [comment]
Super weird, I thought I pushed it, just checked and Cocoapods was showing 0.1.0. Then I tried to push it and cocoapods complained that it won't accept a duplicate version and now the website shows 1.1.0. 

Very odd 🙈 But at least now it seems to be up to date, thanks for pointing it out! 😊
