### ISSUE TITLE
'Error' is ambiguous for type lookup in this context

### ISSUE THREAD

**Issue by GerdC** [kiliankoe/Karte#16]
This simple code leads to a compiler error:  `'Error' is ambiguous for type lookup in this context`

```
import Karte
class CompilterTest {
    var test: Error?
}
```

The reason is that Karte makes the type ambiguous:
```
import Foundation
public enum Error: Swift.Error {
    case unsupportedMode
}
```

It would make code that uses Karte much nicer if it could use the type `Error` as usual.

**Comment by kiliankoe** [comment]
Oh no, thanks Swift 🙈 

Guess I'll have to rename Karte's `Error` type to something else to be unambiguous.
