### ISSUE TITLE
Callback with which app was selected

### ISSUE THREAD

**Issue by julianpomper** [kiliankoe/Karte#22]
Thank you for this library! I think the title speeks for itself.

**Comment by kiliankoe** [comment]
Thanks for the issue! 😊 Sounds like a sensible request, I just added it on the branch `completion-handler`. 

Would you mind giving it a spin or checking it out to see if that works for you? Thanks!

**Comment by julianpomper** [comment]
Works for me! Thanks! 😁

**Comment by kiliankoe** [comment]
Awesome, I'll go ahead and merge and release a new version then 😊
