### ISSUE TITLE
Rename Location as KarteLocation

### ISSUE THREAD

**Issue by JosselinOudry** [kiliankoe/Karte#28]
Hi there,

Thanks for making this great library. I was wondering though whether you could rename `public struct Location {} `into `public struct KarteLocation {}`. We are using a custom Location class in our code and using Karte creates a naming collision with this class.

Thanks in advance.

**Comment by kiliankoe** [comment]
Argh, I thought Swift's namespacing should take care of this, but it seems the type `Karte` overrides the namespace making this impossible.

**Comment by kiliankoe** [comment]
I just pushed version 3.0.0 that renames this as you proposed. Thanks for the heads up!

**Comment by JosselinOudry** [comment]
Awesome! Thanks for responding and making the change so quickly.
