### ISSUE TITLE
Rename App

### ISSUE THREAD

**Issue by fluidsonic** [kiliankoe/Karte#29]
Thanks for the nice library!

Unfortunately just like #28 the name `App` is way too generic and causes an unresolvable collision for us.

Either `App` should be renamed to `KarteApp` / `NavigationApp` / … or `public enum Karte` should be renamed to something different from the module so that any kind of conflict can be resolved e.g. by using `Karte.App`.

Or maybe nest `App` and `Location` etc inside the `Karte` enum so that everything must always be qualified (`Karte.Location`, `Karte.App` etc.)

**Comment by kiliankoe** [comment]
I like the idea of moving the questionable named types into `Karte`, even though that is a bit more verbose when using them, it's closer to how it should be if the namespace weren't overridden. Thanks for the suggestion! 👍

**Comment by kiliankoe** [comment]
fixed with 8cded8997540e9607ef526dfaeb35055a96494e8

**Comment by kiliankoe** [comment]
I just pushed version 4.0.0 with your suggested changes, thanks again 😊

**Comment by fluidsonic** [comment]
Thank you 🙏
