### ISSUE TITLE
actionSheet issue with presentPicker Xcode 11

### ISSUE THREAD

**Issue by cihadhoruzoglu** [kiliankoe/Karte#32]
Hello,

I'm trying to use presentPicker with action sheet, it works but when I return app, title and message stays and can't close the action sheet. Here is my code

 ```swift
@IBAction func navigationTapped(_ sender: Any) {
        let coordinate = CLLocationCoordinate2D(latitude: 52.5162746, longitude: 13.3755153)
        let berlin = Karte.Location(name: "Brandenburger Tor Berlin", coordinate: coordinate)
        let actionSheetVC = UIAlertController(title: "Title", message: "Please Select an Option", preferredStyle: .actionSheet)
        

        self.present(actionSheetVC, animated: true)
        Karte.presentPicker(destination: berlin, presentOn: actionSheetVC)
    }
```

When I clicked button it shows up available maps;
![IMG_9714](https://user-images.githubusercontent.com/1528616/62933763-a245b980-bdcb-11e9-92a5-500cd2c9aae1.PNG)

When I return app screen looks like this;
![IMG_9715](https://user-images.githubusercontent.com/1528616/62933791-b2f62f80-bdcb-11e9-88f3-d372cc63f3d9.PNG)

Am I using action sheet with wrong way?

**Comment by kiliankoe** [comment]
Hi 👋 

Karte already creates the UIAlertController using the actionSheet style for you, there's no need to create one manually and then try and present Karte on top of that.

Try doing something like the following:

```swift
@IBAction func navigationTapped(_ sender: Any) {
       let coordinate = CLLocationCoordinate2D(latitude: 52.5162746, longitude: 13.3755153)
       let berlin = Karte.Location(name: "Brandenburger Tor Berlin", coordinate: coordinate)

       Karte.presentPicker(destination: berlin, presentOn: self)
   }
```

**Comment by cihadhoruzoglu** [comment]
Hi,

Thank you, your solution worked :)
