### ISSUE TITLE
Karte Does not compile with destination Apple Vision Pro

### ISSUE THREAD

**Issue by GerdC** [kiliankoe/Karte#38]
Karte does not compile with destination 'Apple Vision Pro' (Destination Apple Pro /Designed for iPad is no problem.

Problem is this code in enum Karte:

        if #available(iOS 10.0, *) {
            UIApplication.shared.open(url, completionHandler: nil)
        } else {
            UIApplication.shared.openURL(url)
        }

`UIApplication.shared.openURL(url)` isn't available in visionOS

**Comment by kiliankoe** [comment]
Hey @GerdC, thanks for the report! 

@lightsprint09 as you recently added visionOS to the list of supported platforms, do you happen to know how this can be used there?

**Comment by GerdC** [comment]
I cloned Karte, and the cloned version compiles due to this fix

    https://github.com/kiliankoe/Karte/pull/37

which is in a separate branch and not part of the main branch: 

    https://github.com/kiliankoe/Karte/branches

**Comment by kiliankoe** [comment]
The change was merged into `main`, but I forgot to push a tag with that change. I just pushed `4.2.0`, so SwiftPM should pull that in by default now :)

**Comment by GerdC** [comment]
I confirm that it works now, thanks :-)
This is the second of the packages I use where just a release was missing :-)

**Comment by kiliankoe** [comment]
Awesome, glad to know it now works! If you're willing to share what you're working on that uses this on visionOS, I'd be super curious! :)

**Comment by GerdC** [comment]
Just looking what happens if I ran my tourist app natively. 
Two more missing libraries that don't compile yet, before I know :-) 
With destination "Apple Vision Pro (Designed for iPad)" it already runs nicely. https://attractions-map.com/en/barcelona_overview

**Comment by kiliankoe** [comment]
Oh, very cool! Thanks for sharing!
